/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'diverse' : IDL.Null,
});
export const Patient = IDL.Record({
  'birthdate' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'phoneNumber' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPatient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Gender, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'getAllPatientsSorted' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
  'updatePatient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Gender, IDL.Text, IDL.Text],
      [Patient],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'diverse' : IDL.Null,
  });
  const Patient = IDL.Record({
    'birthdate' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'phoneNumber' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    'addPatient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Gender, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'getAllPatientsSorted' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
    'updatePatient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Gender, IDL.Text, IDL.Text],
        [Patient],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };